In [1]:
import torch

<br>

### 全连接层（线性层）

In [2]:
# 指定输入以及输出神经元的数量，创建全连接层
linear = torch.nn.Linear(in_features=10, out_features=5)

In [3]:
# 创建好全连接层后，会自动初始化权重与偏置
linear.weight, linear.bias

(Parameter containing:
 tensor([[ 1.6204e-01, -2.0444e-01, -1.2897e-02,  1.6852e-01,  2.9327e-01,
          -1.0507e-01,  8.5197e-02, -8.1483e-02,  1.0794e-01, -1.1018e-01],
         [ 2.7556e-01,  3.5181e-02,  1.7725e-01, -1.5533e-03, -4.9809e-02,
           1.8827e-01, -2.3475e-01,  1.0436e-01,  3.4916e-02, -1.4363e-01],
         [ 1.5250e-01,  3.1006e-01, -1.0069e-01, -3.7223e-02,  2.8846e-01,
           3.1428e-01, -1.3007e-01,  2.4839e-01,  7.2949e-02,  2.2329e-01],
         [ 6.8134e-02, -2.6406e-01,  1.3295e-01, -2.2816e-01,  1.9616e-01,
          -2.9166e-01,  2.7269e-02,  1.4765e-02, -2.2855e-04, -2.2411e-04],
         [ 9.3534e-03, -5.4455e-02, -9.8700e-02, -2.3186e-05, -2.6181e-01,
          -2.8278e-02,  6.2345e-02, -2.1410e-01, -7.6263e-02,  2.3914e-01]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.1452, -0.2504,  0.1929,  0.2126,  0.2083], requires_grad=True))

In [4]:
# 调用全连接层的正向传播方法（从输入到输出）
x = torch.arange(30, dtype=torch.float32).reshape(3, 10)    # 3 个样本，每个样本 10 个输入
output = linear(x)                                          # 通过调用 call 魔法方法即可实现正向传播，获取输出
print(output.shape)                                         # 分别得到 3 个样本的输出，每个样本对应 5 个输出

torch.Size([3, 5])


<br>

### ReLU层

In [5]:
# 直接创建 ReLU 层，不需要任何参数
relu = torch.nn.ReLU()

# 该层也没有任何模型参数，只是单纯的对输入的任何元素施加 ReLU 函数

In [6]:
# 调用 ReLU 层
x = torch.tensor([1, 2, -3, -0.5])
output = relu(x)                    # 也是通过调用 call 魔法方法来实现正向传播
print(output)

tensor([1., 2., 0., 0.])


<br>

### Sigmoid层

In [7]:
# 整体使用方法与 ReLU 层类似
sigmoid = torch.nn.Sigmoid()          # 创建 Sigmoid 层
x = torch.tensor([1, 2, -3, -0.5])    # 测试样本
output = sigmoid(x)                   # 通过调用 call 魔法方法实现正向传播
print(output)                         # 相当于对每一个输入元素调用 Sigmoid 函数

tensor([0.7311, 0.8808, 0.0474, 0.3775])


<br>

### Softmax层

In [8]:
# 指定应用 Softmax 函数的维度，并创建 Softmax 层
softmax = torch.nn.Softmax(dim=1)

# 一般认为一行表示一个样本，对每一行应用 Softmax 函数（dim = 1）
# 即最终各行元素之和均为 1

In [9]:
x = torch.randn(3, 6)    # 3 个样本，6 个输出（在分类任务中表示对 6 个类别的输出）
output = softmax(x)      # 在每一行元素上应用 Softmax 函数（得到对应 6 个类别的概率）
print(output)

tensor([[0.5016, 0.1687, 0.1253, 0.0173, 0.1146, 0.0726],
        [0.0908, 0.0475, 0.0767, 0.3466, 0.3754, 0.0630],
        [0.3311, 0.1088, 0.0659, 0.0915, 0.1738, 0.2288]])


In [10]:
output.sum(dim=1)      # 各行元素之和均为 1

tensor([1.0000, 1.0000, 1.0000])

<br>

### 卷积层

In [11]:
'''
卷积运算用的最多的是二维卷积（对图像进行处理）
其中输入、输出数据的维度顺序为 (N, C, H, W)

in_channels    -- 输入数据的通道数，也是核的通道数
out_channels   -- 输出数据的通道数，也是核的个数
kernel_size    -- 核的大小
stride         -- 卷积运算的步幅
padding        -- 对输入数据的填充
'''

# 通过指定卷积层的参数来创建卷积层
convolution = torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0)

In [12]:
# 创建好卷积层后，会自动初始化好模型参数（卷积核 和 偏置）
convolution.weight, convolution.bias

(Parameter containing:
 tensor([[[[ 0.1534,  0.1777, -0.1103],
           [ 0.1747,  0.1320, -0.0668],
           [ 0.1125,  0.1222,  0.1434]],
 
          [[ 0.0575,  0.1118, -0.1237],
           [ 0.1854,  0.1912,  0.0103],
           [ 0.0679,  0.0738,  0.1576]],
 
          [[ 0.1380, -0.1378,  0.0348],
           [ 0.0352,  0.0284, -0.0085],
           [-0.0561, -0.1280, -0.0003]]],
 
 
         [[[ 0.0097,  0.1286, -0.0472],
           [-0.1360,  0.0547,  0.1376],
           [-0.1850, -0.1543,  0.1505]],
 
          [[ 0.1173,  0.1756, -0.1196],
           [-0.0359, -0.0743, -0.1007],
           [-0.0190,  0.0543,  0.1252]],
 
          [[ 0.1004, -0.1186,  0.0975],
           [ 0.0920,  0.1349, -0.0147],
           [ 0.1074, -0.0073, -0.0664]]],
 
 
         [[[-0.0838,  0.1028, -0.0808],
           [ 0.1042,  0.0259,  0.1161],
           [ 0.0499, -0.0709, -0.0811]],
 
          [[-0.0486,  0.1491, -0.0394],
           [ 0.0668,  0.1419,  0.1181],
           [-0.1490,  0.1301, 

In [13]:
x = torch.randn(1, 3, 32, 32)     # 模拟 1 个大小为 32 * 32 的 3 通道（RGB）彩色图像数据
output = convolution(x)           # 通过调用 call 魔法方法进行卷积层的正向传播
print(output.shape)               # 可以得到通道数等于核的个数的新数据

torch.Size([1, 6, 30, 30])


<br>

### （最大）池化层

In [14]:
'''
对二维卷积层输出数据进行池化的池化层也一定是二维的
其中输入、输出数据的维度顺序为 (N, C, H, W)
池化不会改变输入数据的通道数，只是精炼数据，缩小长与宽（在每个样本的每一个通道对应的特征图上分别进行精炼数据）

kernel_size    -- 池化运算的窗口大小
stride         -- 窗口移动的步幅
padding        -- 对输入数据的填充
'''
pool = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0)

# 最大池化是提取窗口内的最大值（在图像处理上用的很多）
# 池化层也是没有模型参数的，像激活函数层一样，只是对输入数据做指定的运算操作

In [15]:
x = torch.randn(2, 2, 3, 3)   # 2 个大小为 3 * 3 、通道数为 2 的数据
x

tensor([[[[-0.8901,  1.4404, -0.1949],
          [-0.9262,  2.0766, -0.0273],
          [ 1.5320,  0.3519,  0.0425]],

         [[-0.1658,  0.3645, -0.6759],
          [ 0.0734, -1.3039, -0.4407],
          [-2.2038, -0.2539,  0.8688]]],


        [[[ 2.1428, -1.0313,  1.2831],
          [ 1.4973, -0.2758,  0.3096],
          [-1.3119, -0.1408,  0.5046]],

         [[ 0.6676,  0.3295, -0.1464],
          [-1.2856, -0.8622, -0.3977],
          [-0.0124, -1.2191, -1.3990]]]])

In [16]:
output = pool(x)       # 调用池化层的 call 魔法方法来进行正向传播
print(output.shape)    # 只调整数据的长宽，通道数和样本数是不变的
output

torch.Size([2, 2, 2, 2])


tensor([[[[ 2.0766,  2.0766],
          [ 2.0766,  2.0766]],

         [[ 0.3645,  0.3645],
          [ 0.0734,  0.8688]]],


        [[[ 2.1428,  1.2831],
          [ 1.4973,  0.5046]],

         [[ 0.6676,  0.3295],
          [-0.0124, -0.3977]]]])

<br>

### 自适应平均池化层

In [21]:
# 通过指定输出数据的 H * W，内部会自动计算出合适的池化窗口大小和步幅
global_avg_pool = torch.nn.AdaptiveAvgPool2d((1, 1))

# 池化过程跟普通池化一样

In [ ]:
x = torch.randn(2, 2, 2, 2)
output = global_avg_pool(x)   # 池化不改变样本数和通道数
print(output.shape)

torch.Size([2, 2, 1, 1])


<br>

### Flatten层

In [17]:
# 创建 Flatten 层
flatten = torch.nn.Flatten()

# 用于将每一个样本对应的数据拉平成一维数组
# 常用于对卷积层的输出数据作转换，输入到全连接层中

In [18]:
x = torch.randn(10, 3, 4, 4)
output = flatten(x)
print(output.shape)

torch.Size([10, 48])


<br>

### Dropout层

<br>

### BatchNorm层

In [ ]:
torch.nn.BatchNorm1d

<br>

### MSE损失层

In [19]:
# 创建 MSE 损失层
mseloss = torch.nn.MSELoss()

# 要求输入的预测数据与真实数据的形状一致
# 计算对应位置差的平方和
x = torch.randn(3, 4)
label = torch.rand(3, 4)

# 通过调用损失层的 call 魔法方法进行正向传播
loss = mseloss(x, label)
print(loss)

tensor(1.1662)


<br>

### 交叉熵损失层

In [20]:
# 创建交叉熵损失层（交叉熵损失在分类问题中使用的较多）
crossentropyloss = torch.nn.CrossEntropyLoss()

# 预测数据形状为 (N, M)，表示 N 个样本对应是 M 个类别的概率
x = torch.tensor([[0.1, 0.2, 0.7],
                  [0.3, 0.4, 0.3]], dtype=torch.float32)

# 真实数据形状为 (N,)，表示 N 个样本的真实类别是哪一个（编号从 0 到 M - 1）
label1 = torch.tensor([2, 1])

# 真实数据也可以是预测数据同样的形状，表示各个样本是各种类型的概率
label2 = torch.tensor([[0, 0, 1],
                       [0, 1, 0]], dtype=torch.float32)

# 通过调用损失层的 call 魔法方法进行正向传播
loss1 = crossentropyloss(x, label1)
loss2 = crossentropyloss(x, label2)
print(loss1, loss2)

# 注意：这个交叉熵损失层再内部是先对数据应用 Softmax 函数的，故使用时不需要额外在其前面添加 Softmax 层

tensor(0.9005) tensor(0.9005)
