In [1]:
import torch

<br>

### 全连接层（线性层）

In [2]:
# 指定输入以及输出神经元的数量，创建全连接层
linear = torch.nn.Linear(in_features=10, out_features=5)

In [3]:
# 创建好全连接层后，会自动初始化权重与偏置
linear.weight, linear.bias

(Parameter containing:
 tensor([[-0.0455,  0.3008,  0.1281,  0.2621,  0.0457,  0.3075, -0.2405,  0.0377,
          -0.1661, -0.2990],
         [-0.2488,  0.2213, -0.3131,  0.1024, -0.2728,  0.2503, -0.2249, -0.0123,
          -0.1601, -0.1512],
         [-0.2920,  0.0107, -0.3029,  0.2823,  0.1365, -0.2969,  0.2674,  0.1127,
          -0.2489,  0.2587],
         [ 0.0882,  0.0691, -0.0028,  0.0456, -0.2048,  0.2760,  0.1824, -0.0427,
          -0.0581,  0.0818],
         [-0.0637,  0.2225, -0.0490,  0.2941,  0.0802,  0.1224,  0.0058,  0.0408,
           0.2100, -0.1777]], requires_grad=True),
 Parameter containing:
 tensor([-0.0460,  0.3107, -0.1693, -0.1184, -0.0231], requires_grad=True))

In [4]:
# 调用全连接层的正向传播方法（从输入到输出）
x = torch.arange(30, dtype=torch.float32).reshape(3, 10)    # 3 个样本，每个样本 10 个输入
output = linear(x)                                          # 通过调用 call 魔法方法即可实现正向传播，获取输出
print(output.shape)                                         # 分别得到 3 个样本的输出，每个样本对应 5 个输出

torch.Size([3, 5])


<br>

### ReLU层

In [5]:
# 直接创建 ReLU 层，不需要任何参数
relu = torch.nn.ReLU()

# 该层也没有任何模型参数，只是单纯的对输入的任何元素施加 ReLU 函数

In [6]:
# 调用 ReLU 层
x = torch.tensor([1, 2, -3, -0.5])
output = relu(x)                    # 也是通过调用 call 魔法方法来实现正向传播
print(output)

tensor([1., 2., 0., 0.])


<br>

### Sigmoid层

In [7]:
# 整体使用方法与 ReLU 层类似
sigmoid = torch.nn.Sigmoid()          # 创建 Sigmoid 层
x = torch.tensor([1, 2, -3, -0.5])    # 测试样本
output = sigmoid(x)                   # 通过调用 call 魔法方法实现正向传播
print(output)                         # 相当于对每一个输入元素调用 Sigmoid 函数

tensor([0.7311, 0.8808, 0.0474, 0.3775])


<br>

### Softmax层

In [8]:
# 指定应用 Softmax 函数的维度，并创建 Softmax 层
softmax = torch.nn.Softmax(dim=1)

# 一般认为一行表示一个样本，对每一行应用 Softmax 函数（dim = 1）
# 即最终各行元素之和均为 1

In [9]:
x = torch.randn(3, 6)    # 3 个样本，6 个输出（在分类任务中表示对 6 个类别的输出）
output = softmax(x)      # 在每一行元素上应用 Softmax 函数（得到对应 6 个类别的概率）
print(output)

tensor([[0.0341, 0.0603, 0.1581, 0.0621, 0.5418, 0.1436],
        [0.1167, 0.1364, 0.2221, 0.1870, 0.2396, 0.0981],
        [0.0561, 0.1891, 0.1158, 0.2129, 0.1480, 0.2782]])


In [10]:
output.sum(dim=1)      # 各行元素之和均为 1

tensor([1., 1., 1.])

<br>

### 卷积层

In [11]:
'''
卷积运算用的最多的是二维卷积（对图像进行处理）
其中输入、输出数据的维度顺序为 (N, C, H, W)

in_channels    -- 输入数据的通道数，也是核的通道数
out_channels   -- 输出数据的通道数，也是核的个数
kernel_size    -- 核的大小
stride         -- 卷积运算的步幅
padding        -- 对输入数据的填充
'''

# 通过指定卷积层的参数来创建卷积层
convolution = torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0)

In [12]:
# 创建好卷积层后，会自动初始化好模型参数（卷积核 和 偏置）
convolution.weight, convolution.bias

(Parameter containing:
 tensor([[[[-0.0218,  0.0320,  0.1615],
           [-0.0820, -0.1020, -0.1386],
           [-0.0526,  0.1307, -0.1749]],
 
          [[-0.0671, -0.1082,  0.1593],
           [-0.1356, -0.0759,  0.1299],
           [-0.1051,  0.1729,  0.1365]],
 
          [[-0.0749,  0.0309,  0.1770],
           [-0.0815, -0.0419,  0.0655],
           [ 0.0554,  0.1530,  0.0756]]],
 
 
         [[[-0.1360,  0.0424, -0.0903],
           [-0.1453, -0.1251, -0.1236],
           [ 0.0097, -0.1253, -0.1711]],
 
          [[-0.0698,  0.0930, -0.1879],
           [-0.1744, -0.0228,  0.0995],
           [ 0.0508, -0.1039, -0.1312]],
 
          [[ 0.1577,  0.1495,  0.1759],
           [ 0.1540,  0.0169,  0.0583],
           [-0.1777,  0.0854,  0.1430]]],
 
 
         [[[ 0.0044,  0.0039, -0.1510],
           [-0.1274, -0.0105,  0.0777],
           [ 0.0142, -0.1594, -0.1210]],
 
          [[-0.0354, -0.1450, -0.0793],
           [-0.1736,  0.1643,  0.0766],
           [-0.0761, -0.1523, 

In [13]:
x = torch.randn(1, 3, 32, 32)     # 模拟 1 个大小为 32 * 32 的 3 通道（RGB）彩色图像数据
output = convolution(x)           # 通过调用 call 魔法方法进行卷积层的正向传播
print(output.shape)               # 可以得到通道数等于核的个数的新数据

torch.Size([1, 6, 30, 30])


<br>

### （最大）池化层

In [14]:
'''
对二维卷积层输出数据进行池化的池化层也一定是二维的
其中输入、输出数据的维度顺序为 (N, C, H, W)
池化不会改变输入数据的通道数，只是精炼数据，缩小长与宽（在每个样本的每一个通道对应的特征图上分别进行精炼数据）

kernel_size    -- 池化运算的窗口大小
stride         -- 窗口移动的步幅
padding        -- 对输入数据的填充
'''
pool = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0)

# 最大池化是提取窗口内的最大值（在图像处理上用的很多）
# 池化层也是没有模型参数的，像激活函数层一样，只是对输入数据做指定的运算操作

In [15]:
x = torch.randn(2, 2, 3, 3)   # 2 个大小为 3 * 3 、通道数为 2 的数据
x

tensor([[[[-1.4521, -0.0928,  1.8533],
          [ 0.3491, -1.3944,  2.1962],
          [-0.6643, -0.3087,  0.2284]],

         [[ 1.4465, -0.6853,  1.0208],
          [-0.9505,  0.5066,  1.2384],
          [-0.4284,  0.8077, -0.1590]]],


        [[[ 0.7662, -0.7766, -0.5460],
          [ 0.6284, -0.0870, -0.6088],
          [-1.2213,  0.3833, -0.4907]],

         [[ 0.8547,  0.6421, -1.1427],
          [-0.7311,  1.4001,  0.5353],
          [-0.2117,  0.4510,  0.8516]]]])

In [16]:
output = pool(x)       # 调用池化层的 call 魔法方法来进行正向传播
print(output.shape)    # 只调整数据的长宽，通道数和样本数是不变的
output

torch.Size([2, 2, 2, 2])


tensor([[[[ 0.3491,  2.1962],
          [ 0.3491,  2.1962]],

         [[ 1.4465,  1.2384],
          [ 0.8077,  1.2384]]],


        [[[ 0.7662, -0.0870],
          [ 0.6284,  0.3833]],

         [[ 1.4001,  1.4001],
          [ 1.4001,  1.4001]]]])

<br>

### Flatten层

In [ ]:
# 创建 Flatten 层
flatten = torch.nn.Flatten()

# 用于将每一个样本对应的数据拉平成一维数组
# 常用于对卷积层的输出数据作转换，输入到全连接层中

In [18]:
x = torch.randn(10, 3, 4, 4)
output = flatten(x)
print(output.shape)

torch.Size([10, 48])


<br>

### Dropout层

<br>

### BatchNorm层

<br>

### MSE损失层

In [19]:
# 创建 MSE 损失层
mseloss = torch.nn.MSELoss()

# 要求输入的预测数据与真实数据的形状一致
# 计算对应位置差的平方和
x = torch.randn(3, 4)
label = torch.rand(3, 4)

# 通过调用损失层的 call 魔法方法进行正向传播
loss = mseloss(x, label)
print(loss)

tensor(0.7880)


<br>

### 交叉熵损失层

In [20]:
# 创建交叉熵损失层（交叉熵损失在分类问题中使用的较多）
crossentropyloss = torch.nn.CrossEntropyLoss()

# 预测数据形状为 (N, M)，表示 N 个样本对应是 M 个类别的概率
x = torch.tensor([[0.1, 0.2, 0.7],
                  [0.3, 0.4, 0.3]], dtype=torch.float32)

# 真实数据形状为 (N,)，表示 N 个样本的真实类别是哪一个（编号从 0 到 M - 1）
label1 = torch.tensor([2, 1])

# 真实数据也可以是预测数据同样的形状，表示各个样本是各种类型的概率
label2 = torch.tensor([[0, 0, 1],
                       [0, 1, 0]], dtype=torch.float32)

# 通过调用损失层的 call 魔法方法进行正向传播
loss1 = crossentropyloss(x, label1)
loss2 = crossentropyloss(x, label2)
print(loss1, loss2)

# 注意：这个交叉熵损失层再内部是先对数据应用 Softmax 函数的，故使用时不需要额外在其前面添加 Softmax 层

tensor(0.9005) tensor(0.9005)
